/* 🤖 this file was generated by svg-to-ts */
export * from './build/clientLogo-logo_adyen.icon';
export * from './build/clientLogo-logo_allegro.icon';
export * from './build/clientLogo-logo_cambridge-satchel.icon';
export * from './build/clientLogo-logo_canon.icon';
export * from './build/clientLogo-logo_founder-lightning.icon';
export * from './build/clientLogo-logo_home-philosophy.icon';
export * from './build/clientLogo-logo_latetrip.icon';
export * from './build/clientLogo-logo_m87.icon';
export * from './build/clientLogo-logo_orsay.icon';
export * from './build/clientLogo-logo_payu.icon';
export * from './build/clientLogo-logo_pepsico.icon';
export * from './build/clientLogo-logo_prodigi.icon';
export * from './build/clientLogo-logo_rolla.icon';
export * from './build/clientLogo-logo_royaleson.icon';
