import { BlogCards } from "@/components/blog/blog-cards";
import { GetInTouch } from "@/components/contact/get-in-touch";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { MainNavigation } from "@/components/shared/main-navigation";
import { safiro } from "@/constants/fonts";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={safiro.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <MainNavigation />
          <main>{children}</main>
          <div className="relative z-[100]">
            <BlogCards />
            <GetInTouch />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
